### ISSUE TITLE
CRUD Natureza de Despesa e Subitens

### ISSUE THREAD

**Issue by helesjunior** [helesjunior/sigex#3]

**Comment by helesjunior** [comment]
Criar CRUD para Natureza de Despesas e Subitens (Igual a do Código Itens)

Tabelas:

expense_kinds_table
expense_kind_sub_items_table

**Comment by helesjunior** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CRUD Natureza de Despesa e Subitens](https://trello.com/c/pY85hLtu/3-crud-natureza-de-despesa-e-subitens)

**Comment by asathler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CRUD Natureza da despesa](https://trello.com/c/90L6d917/13-crud-natureza-da-despesa)

**Comment by asathler** [comment]
Em duplicidade com #8 .
Issue encerrada!
