### ISSUE TITLE
CRUD formulários de cadastro de credor, contrato, processo e empenho

### ISSUE THREAD

**Issue by ricardokato** [helesjunior/sigex#4]
Drafts dos formulários:
a) credor: https://marvelapp.com/project/5153841/design/72601583
b) contrato: https://marvelapp.com/project/5153841/design/72600490
c) processo: https://marvelapp.com/project/5153841/design/72599778
d) empenho: https://marvelapp.com/project/5153841/design/72517723

Sugestão: desenvolver páginas conforme a sequência acima, pois a última página depende das anteriores e assim por diante.

Há diversos campos cujas opções são aquelas do Siafi.

**Comment by asathler** [comment]
Itens desmembrados em issues individuais
